/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', event => {
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  self.clients.claim();
});

self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-incidents') {
    console.log('Service Worker: Received sync event for incidents.');
    event.waitUntil(syncIncidents());
  }
});

async function syncIncidents() {
  const db = await openDb();
  const tx = db.transaction('incident-outbox', 'readonly');
  const store = tx.objectStore('incident-outbox');
  const allIncidentsRequest = store.getAll();

  const allIncidents = await new Promise<any[]>((resolve, reject) => {
    allIncidentsRequest.onsuccess = () => resolve(allIncidentsRequest.result);
    allIncidentsRequest.onerror = () => reject(allIncidentsRequest.error);
  });

  return Promise.all(allIncidents.map(async (incident) => {
    try {
      const response = await fetch('/api/incidents', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(incident),
      });

      if (response.ok) {
        console.log('Service Worker: Synced incident to server:', incident.id);
        const deleteTx = db.transaction('incident-outbox', 'readwrite');
        const deleteStore = deleteTx.objectStore('incident-outbox');
        const deleteRequest = deleteStore.delete(incident.id);
        await new Promise<void>((resolve, reject) => {
          deleteRequest.onsuccess = () => resolve();
          deleteRequest.onerror = () => reject(deleteRequest.error);
        });
      } else {
        console.error('Service Worker: Failed to sync incident:', incident.id, response);
      }
    } catch (error) {
      console.error('Service Worker: Error syncing incident:', incident.id, error);
    }
  })).then(() => {
    console.log('Service Worker: Finished incident sync.');
  });
}

// Minimal IDB helper to avoid importing the whole library into the SW
function openDb() {
  return new Promise<IDBDatabase>((resolve, reject) => {
    const request = indexedDB.open('mas-bosque-db', 1);
    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);
    request.onupgradeneeded = (event) => {
      const db = (event.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains('incident-outbox')) {
        db.createObjectStore('incident-outbox', { keyPath: 'id' });
      }
    };
  });
}
